global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'gpu-metrics'
    static_configs:
      - targets: ['host.docker.internal:9402']
    metrics_path: '/metrics'

  - job_name: 'nvidia-gpu'
    static_configs:
      - targets: ['host.docker.internal:9835']  # NVIDIA DCGM exporter port
